### ISSUE TITLE
[component] core input

### ISSUE THREAD

**Issue by Enkhjin0816** [HOP-3-Duluu/School_Vibes#8]

**Comment by billduluu** [comment]
Description sanaa shu unshaad iimrhu um bichj baiwal hiij baiga hund oilgomjtoi bas todrhoi daraan zasaad baihku bh gj bodjin

1. Input 2 uur turliin input baih yostoi 
2. Design iim2 baiga gj zurag tawidag ch umuu te
3. Dynamic input iim2 baih yostoi gsn jisheech umuu 

@Nasaa1234  @Tu98022410 @telmuun11 @Enkhjin0816
